export const KEY_STORAGE_USER = {
  SET_DATA_USER: 'SET_DATA_USER',
}
export const KEY_STORAGE_CART = {
  SET_DATA_CART: 'SET_DATA_CART',
}
export const KEY_STORAGE_PRODUCT = {
  SET_DATA_PRODUCT: 'SET_DATA_PRODUCT',
}
export const KEY_STORAGE_RANDOM = {
  SET_DATA_RANDOM: 'SET_DATA_RANDOM',
}
